### ISSUE TITLE
Not working with PHP7

### ISSUE THREAD

**Issue by frufin** [dan-da/cdc_audit#5]
Unfortunately, PHP7 now uses PDO.
Did you update your scripts for that version of PHP ?

**Comment by dan-da** [comment]
thanks for the report.   Unfortunately, I don't have time to work on it just now.

This would be a good little project for someone to submit a pull request.

Otherwise I will leave it open until am able...

**Comment by dan-da** [comment]
PDO is probably more future proof however this fixes the issue for php7 and we only care about mysql for this project (the SQL is very mysql specific), so don't need PDO's db agnostic stuff.   might revisit later.
